apiVersion: v1
kind: ConfigMap
metadata:
  name: gen-ai-aa-custom-model-endpoints
  namespace: proj1
data:
  config.yaml: |
    providers:
      inference:
        - provider_id: granite-embed-provider
          provider_type: remote::passthrough
          config:
            base_url: http://granite-embedding-r2-predictor.proj1.svc.cluster.local

    registered_resources:
      models:
        - provider_id: granite-embed-provider
          model_id: RedHatAI/granite-embedding-english-r2
          model_type: embedding
          metadata:
            display_name: Granite Embedding R2
            embedding_dimension: 768
